# Project ID of the study in the SRA database
srp_id: SRP279492

# Paths to required binaries, download from:
# https://support.10xgenomics.com/single-cell-gene-expression/software/downloads/latest
bamtofastq: "/home/yi/data0/sc_tumor/cellranger/bamtofastq"
cellranger: "/home/yi/data0/sc_tumor/cellranger/cellranger-6.0.1/bin/cellranger"

# Path of folder containing 10x-compatible transcriptome reference
ref_transcriptome:
  human: "/home/yi/data0/sc_tumor/cellranger/refdata-gex-GRCh38-2020-A"
  mouse: ""
